import { db } from '@/db';
import { dailyNutrition } from '@/db/schema';

async function main() {
    const today = new Date();
    const getDaysAgo = (days: number) => {
        const date = new Date(today);
        date.setDate(date.getDate() - days);
        return date.toISOString().split('T')[0];
    };

    const sampleNutrition = [
        // User 1 (Sarah - losing weight, target ~1600 calories)
        {
            userId: 'user_1',
            date: getDaysAgo(6),
            caloriesConsumed: 1720,
            proteinG: 105,
            carbsG: 175,
            fatG: 62,
            fiberG: 32,
            waterMl: 2400,
            createdAt: new Date(getDaysAgo(6)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(5),
            caloriesConsumed: 1680,
            proteinG: 98,
            carbsG: 168,
            fatG: 58,
            fiberG: 30,
            waterMl: 2600,
            createdAt: new Date(getDaysAgo(5)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(4),
            caloriesConsumed: 1650,
            proteinG: 92,
            carbsG: 165,
            fatG: 55,
            fiberG: 28,
            waterMl: 2500,
            createdAt: new Date(getDaysAgo(4)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(3),
            caloriesConsumed: 1610,
            proteinG: 88,
            carbsG: 158,
            fatG: 52,
            fiberG: 27,
            waterMl: 2700,
            createdAt: new Date(getDaysAgo(3)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(2),
            caloriesConsumed: 1580,
            proteinG: 85,
            carbsG: 152,
            fatG: 50,
            fiberG: 29,
            waterMl: 2800,
            createdAt: new Date(getDaysAgo(2)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(1),
            caloriesConsumed: 1540,
            proteinG: 82,
            carbsG: 148,
            fatG: 48,
            fiberG: 31,
            waterMl: 2600,
            createdAt: new Date(getDaysAgo(1)).toISOString(),
        },
        {
            userId: 'user_1',
            date: getDaysAgo(0),
            caloriesConsumed: 1510,
            proteinG: 80,
            carbsG: 145,
            fatG: 46,
            fiberG: 33,
            waterMl: 2700,
            createdAt: new Date(getDaysAgo(0)).toISOString(),
        },

        // User 2 (Mike - building muscle, target ~2800 calories)
        {
            userId: 'user_2',
            date: getDaysAgo(6),
            caloriesConsumed: 2850,
            proteinG: 210,
            carbsG: 340,
            fatG: 92,
            fiberG: 36,
            waterMl: 3500,
            createdAt: new Date(getDaysAgo(6)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(5),
            caloriesConsumed: 2920,
            proteinG: 215,
            carbsG: 350,
            fatG: 95,
            fiberG: 38,
            waterMl: 3600,
            createdAt: new Date(getDaysAgo(5)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(4),
            caloriesConsumed: 2780,
            proteinG: 205,
            carbsG: 330,
            fatG: 88,
            fiberG: 34,
            waterMl: 3400,
            createdAt: new Date(getDaysAgo(4)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(3),
            caloriesConsumed: 2890,
            proteinG: 212,
            carbsG: 345,
            fatG: 93,
            fiberG: 37,
            waterMl: 3700,
            createdAt: new Date(getDaysAgo(3)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(2),
            caloriesConsumed: 2950,
            proteinG: 218,
            carbsG: 355,
            fatG: 97,
            fiberG: 39,
            waterMl: 3800,
            createdAt: new Date(getDaysAgo(2)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(1),
            caloriesConsumed: 2820,
            proteinG: 208,
            carbsG: 335,
            fatG: 90,
            fiberG: 35,
            waterMl: 3500,
            createdAt: new Date(getDaysAgo(1)).toISOString(),
        },
        {
            userId: 'user_2',
            date: getDaysAgo(0),
            caloriesConsumed: 2880,
            proteinG: 213,
            carbsG: 342,
            fatG: 94,
            fiberG: 38,
            waterMl: 3650,
            createdAt: new Date(getDaysAgo(0)).toISOString(),
        },

        // User 3 (Emily - managing diabetes, target ~1800 calories)
        {
            userId: 'user_3',
            date: getDaysAgo(6),
            caloriesConsumed: 1780,
            proteinG: 98,
            carbsG: 185,
            fatG: 62,
            fiberG: 34,
            waterMl: 2500,
            createdAt: new Date(getDaysAgo(6)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(5),
            caloriesConsumed: 1820,
            proteinG: 105,
            carbsG: 192,
            fatG: 65,
            fiberG: 36,
            waterMl: 2600,
            createdAt: new Date(getDaysAgo(5)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(4),
            caloriesConsumed: 1750,
            proteinG: 92,
            carbsG: 178,
            fatG: 58,
            fiberG: 32,
            waterMl: 2400,
            createdAt: new Date(getDaysAgo(4)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(3),
            caloriesConsumed: 1840,
            proteinG: 108,
            carbsG: 195,
            fatG: 67,
            fiberG: 37,
            waterMl: 2700,
            createdAt: new Date(getDaysAgo(3)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(2),
            caloriesConsumed: 1790,
            proteinG: 100,
            carbsG: 182,
            fatG: 63,
            fiberG: 35,
            waterMl: 2550,
            createdAt: new Date(getDaysAgo(2)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(1),
            caloriesConsumed: 1810,
            proteinG: 103,
            carbsG: 188,
            fatG: 64,
            fiberG: 36,
            waterMl: 2650,
            createdAt: new Date(getDaysAgo(1)).toISOString(),
        },
        {
            userId: 'user_3',
            date: getDaysAgo(0),
            caloriesConsumed: 1770,
            proteinG: 96,
            carbsG: 180,
            fatG: 60,
            fiberG: 33,
            waterMl: 2500,
            createdAt: new Date(getDaysAgo(0)).toISOString(),
        },
    ];

    await db.insert(dailyNutrition).values(sampleNutrition);
    
    console.log('✅ Daily nutrition seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});